global:
  seed: 0
  d: 32
  k: 10
  seq_length: 15
  test_set_size: 1024
  track_set_size: 1024
  track_source: test
  output_dir: outputs/
  data_generator:
    _target_: utils.data_generator.RademacherInputGenerator
  # data_generator:
  #   _target_: utils.data_generator.MixtureInputGenerator
  #   num_mix: 32
  #   sigma: 0.0

experiment:
  type: outcome_reward
  name: sup_then_pg_outcome
  enabled: true
  seed: 0
  supervised:
    steps: 1500
    batch_size: 256
    optimizer:
      _target_: torch.optim.SGD
      _partial_: true
      lr: 0.1
    test_every: 50
  pg:
    steps: 1500
    batch_size: 256
    optimizer:
      _target_: torch.optim.SGD
      _partial_: true
      lr: 0.1
    test_every: 50
    track_every: 10
    behavior:
      _target_: utils.behavior_policy.OnPolicyBehavior
  track_initial_quantiles: 15
  supervised_track_histogram_file: sup_hist_outcome.pdf
  supervised_track_histogram_bins: 120
  supervised_track_likelihood_tensor_file: sup_lik_outcome.pt
  likelihood_plot_file: pg_lik_curve_outcome.pdf
  expected_error_plot_file: pg_err_outcome.pdf
